apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-memory-db
  labels:
    app: in-memory-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: in-memory-db
  template:
    metadata:
      labels:
        app: in-memory-db
    spec:
      containers:
        - name: in-memory-db
          image: in-memory-db:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: in-memory-db-service
spec:
  selector:
    app: in-memory-db
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer